/*
389. Find the Difference

You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
 

Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters. 
*/



package Strings;

import java.util.Arrays;

public class Find_the_Difference {
    /*
    Solution 1 
    */
    public char findTheDifference(String s, String t) {
        char[] sch = s.toCharArray();
        char[] tch = t.toCharArray();

        Arrays.sort(sch);
        Arrays.sort(tch);

        for(int i=0; i<sch.length;i++){
            if(sch[i]!=tch[i])
                return tch[i];
        }
        return tch[tch.length-1];
    }
}
